### ISSUE TITLE
TODO List for launch

### ISSUE THREAD

**Issue by bnhansn** [bnhansn/artdirectory#1]
1.
- [x] Header whiteout error

2.
- [x] Make search box white
- [x] Fix spacing
- [x] Add hover for arrows
- [x] Change cursor to an arrow (subcategories and artist names)
- [x] Make artist thumbnail images clickable
- [x] Change search box to say “Search” instead of “Artist’s Name”
- [x] Italicize medium beneath Artist’s Name
- [x] Reinstate white borders around images
- [x] Changing/removing slider bar

3.
- [x] Fix post thumbnail editor
- [x] Fix gallery arrows (so they remain in one spot)
- [x] Title/medium/size (should be beneath gallery, also on Modal 2 by full image gallery)
- [x] Add dots below gallery (to show how many images there are and current image)
- [x] Left Justify Map

Additional Categories Needed
- [x] Contact Info
- [x] Social Icons
- [x] OPEN FRIDAY icon
- [x] Handicap Accessible icon
- [x] Artist Statement (Encompass Artist Statement, Mission Statement, About)
- [x] Additional Info (Blank Header)
- [x] Directions
- [x] General Classes Offered
- [x] Hours

4.
- [x] Make directory fully responsive

**Comment by bnhansn** [comment]
Topics covered in our second meeting:

- [x] Align search box with images
- [x] Make next/prev arrows white on hover--left icons are different sizes though :(
- [x] Vertically align next/prev arrows
- [x] Use gray arrows in thumbnail gallery
- [x] Add icons for open friday/handicap
- [x] Make Artist Statement header configurable
- [x] Remove labels on art description
